# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
#-------------------------
# 사용자 import
#-------------------------

from heroS import *
import datetime

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(814, 666)
        self.mainlog = QtWidgets.QTextBrowser(Dialog)
        self.mainlog.setGeometry(QtCore.QRect(200, 20, 281, 631))
        self.mainlog.setObjectName("mainlog")
        self.sublog1 = QtWidgets.QTextBrowser(Dialog)
        self.sublog1.setGeometry(QtCore.QRect(500, 20, 281, 301))
        self.sublog1.setObjectName("sublog1")
        self.sublog2 = QtWidgets.QTextBrowser(Dialog)
        self.sublog2.setGeometry(QtCore.QRect(500, 350, 281, 301))
        self.sublog2.setObjectName("sublog2")
        self.status02 = QtWidgets.QTextBrowser(Dialog)
        self.status02.setGeometry(QtCore.QRect(30, 460, 161, 191))
        self.status02.setObjectName("status02")
        self.status01 = QtWidgets.QTextBrowser(Dialog)
        self.status01.setGeometry(QtCore.QRect(30, 140, 161, 191))
        self.status01.setObjectName("status01")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(31, 21, 158, 112))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_3)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_7)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 340, 158, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_16)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "계좌상태"))
        self.pushButton_2.setText(_translate("Dialog", "보유현황"))
        self.pushButton_6.setText(_translate("Dialog", "PushButton"))
        self.pushButton_3.setText(_translate("Dialog", "PushButton"))
        self.pushButton_8.setText(_translate("Dialog", "PushButton"))
        self.pushButton_4.setText(_translate("Dialog", "PushButton"))
        self.pushButton_5.setText(_translate("Dialog", "PushButton"))
        self.pushButton_7.setText(_translate("Dialog", "PushButton"))
        self.pushButton_9.setText(_translate("Dialog", "PushButton"))
        self.pushButton_10.setText(_translate("Dialog", "PushButton"))
        self.pushButton_11.setText(_translate("Dialog", "PushButton"))
        self.pushButton_12.setText(_translate("Dialog", "PushButton"))
        self.pushButton_13.setText(_translate("Dialog", "PushButton"))
        self.pushButton_14.setText(_translate("Dialog", "PushButton"))
        self.pushButton_15.setText(_translate("Dialog", "PushButton"))
        self.pushButton_16.setText(_translate("Dialog", "PushButton"))

        #-------------------------------------------------------------
        # 사용자 정의 이벤트 connect
        #-------------------------------------------------------------
        
        self.pushButton.clicked.connect(self.pushButton_clicked)

    #-------------------------------------------------------------
    # 사용자 정의영역
    #-------------------------------------------------------------
    def __init__(self):

        self.heroS = heroS()

         # timer
        self.timer = QTimer()
        self.timer.start(3000)
        self.timer.timeout.connect(self.KOSDAQ_BUY)



        #self.timer2 = QTimer()
        #self.timer2.start(1000)
        #self.timer2.timeout.connect(self.KOSDAQ_SELL)

    


    #-------------------------------------------------------------
    # 사용자 정의함수
    #-------------------------------------------------------------
    def pushButton_clicked(self):
        print("button_clicked")
        self.heroS.getBasicInfo()

    def KOSDAQ_BUY(self):
        
        print("KB_activate")
        list = self.heroS.getSetUpStock(0,0)
        code = str(list[1])
        if(list[0]):
            print(code+" "+"buy signal")
            self.mainlog.append(code+" "+"buy signal")   


    def KOSDAQ_SELL(self):
        
        print("KS_activate")
        list = self.heroS.getSetUpStock(0,1)
        code = str(list[1])
        if(list[0]):
            print(code+" "+"sell signal")
            self.mainlog.append(code+" "+"sell signal")  

    def TRADER(flag,code):
        print("ddd")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
